apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgASgaBlBwz6AK58grzgfsHizomVWAnF4/WiXN/1Dz8YLIYJOm+01lHe2NJF6Naq6ClXwdM41klWAzh3nm8Hizbmrr8JF0mYi2ywGE3CtwVm9rFZOT7mpBGNU5UjP0grEb4Vdo2V8RkQIyLcra9+tYrewIG2W5aTbqkxfZ8S8jrHE52GtjXUcz4SVqZN7tRUSS9+/yLS1nck1x2/DJ7as9h/fk0fHm8J5nhLyxwAzeA//r6wxW8lOasRQ3Wd/7rnzudSaZ05U93WDwMZMgntNnXXCKtFT3+t5GyetRJRzybH03jniCIzaFEJ9cLXSJS7EzpgPhQaSrTtSONf49CZLccldp390Mj1Y5Ln1V5+ntIbzUvXMOAKArif5oiek+Y2uufIQXMH7uIG+HDa/S3tFyX7uaHAKgafKpm0ARTCtARminfu0Xk4Nkz17u6WdYyYxO9XBhyOJ0jzhAXKUJD2l97jd2DkxBPc7BF4SnwvRQsJO1cEssEAtiPHu5NCFMweXECXYuowVfGNBixCTkXYEzXW6dZ5hPTMZNbmF6hgqSOpTgQebNX6FxQ0LyUdHXcMDT23fwLcOif2DGUlqhGpCYJVAQoZluS2IV0CLef9+XZ8LjwQogCToVACwayxRWq+/uilUXIvA+ygbUo4w92AR+pOAsrQoXVsimlSN92FP73SBgqDuhIH4crsjIOQ2HpORitWQ26+Z1QThi2PhhjMM9bN/REP0mD2PFA/Tu0sNzhqtmEJF+jsxgjvybynKCY/yOkmxG+8CWyRWsstHnR+xqSAHcN8oSML8HPvQkSAXdsagbz+vnVcQrwKN6Hqe0zZIUwgFvfuq8EbJlPQbkd+3yEIqwFyiIhl3EXAoScSLzfcLiLyh+PuWT4AOs8VBLZh3FxIFHGtHCPCYwwcIe4v6XoCoJjgSl9vxa0RVsd6+p2gkYLr6ZCJtllexM6bdeaN5r4=
    IBM_ENTITLED_REGISTRY_USER: AgB4+h8pVNoe6+nzzKolGuFXS5muOuSoxQoDjHL8aYeeRZ1hZqsRjGYRnM02s9yKTMel7TmOGT4rE4UYMAqHqfF5WIl6lynk+UTXHGSWH9jBvFkYy/hgfVjPf3YIMK/3gZQjS1P4EDV6OsDQgVWgcyV2PyqCF3nLYUyWiRnrm9fnwHyvn32VdUg67HWSbjjmLMIh9HEphBNNkQukrgCkNWS+uNAXgFjRWqOEjgIyCzuQAlci1RezPh6NbJ+bYxHTcEkjxLJN5hh5dnE7C6vIuYL1FmNGQc8Su7l+NUzJO2gB7FPT0doCRbIipGCWSI3Q8tOjJgqtSJT1fmMKrEMfdK11fcvcaf8l826BbMBO7oXHcA9E3Uo34Ul1jOOh4mZFyNhM9lRO420Do0luOXLXwRpdS9L08i5MmorCJBUAqE0JfnYZ0z3lTYknnvy51LJ7wlylz89LaHcvQ8p5f6qiNJuXh8QXSf7gtteps0rhovDithV6ce6TZ2BFFEhi9027oWJwzeQonTy6ZyUS/xpA8/BPKJwwXMR5jQufTosKwuf87mGgBLQCgaKWUESbSUmD5/jI65Xev406dZYbc+pSCLdCnAC77XBod9HSSiMMBFKYUjapTrCLMKC6RXiBjNXHzyT09meAWwBz8wWFCnHarqtMkvpefAW+Ebd/Li7mj4CKOU8ibxmevzIy9JdBBEktXzfE3g==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

